### ISSUE TITLE
npm run build 失败

### ISSUE THREAD

**Issue by qiuyaofan** [Thunf/wepy-demo-bookmall#9]
{ Error: Cannot find module 'less'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/qiuyaofan/Documents/lianxi/weixin/wepy-demo-bookmall/node_modules/wepy-compiler-less/lib/index.js:20:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.load (/usr/local/lib/node_modules/wepy-cli/lib/loader.js:113:17)
    at Object.loadCompiler (/usr/local/lib/node_modules/wepy-cli/lib/loader.js:69:29)
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-style.js:91:45
    at Array.forEach (<anonymous>) code: 'MODULE_NOT_FOUND' }
[WARNING] 找不到编译器：wepy-compiler-less。
[Error] 未发现相关 less 编译器配置，请检查wepy.config.js文件。

**Comment by qiuyaofan** [comment]
应该是wepy-cli没装成功

**Comment by qiuyaofan** [comment]
知道问题了 
npm install less 后再 npm install wepy-compiler-less 解决

https://github.com/Tencent/wepy/issues/413
